name: Build macOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DRP3D_OPENSSL_LIB_DIR=${{ github.workspace }}/luaclib_src/openssl/lib/mac

    - name: Build
      run: cmake --build build
