name: Build Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libreadline-dev

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DRP3D_OPENSSL_LIB_DIR=${{ github.workspace }}/luaclib-src/openssl/lib/linux

    - name: Build
      run: cmake --build build
